version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=hyggeuser
      - POSTGRES_PASSWORD=hyggepassword
      - POSTGRES_DB=hyggedb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  minio-server:
    image: minio/minio
    depends_on:
      - postgres
    restart: always
    volumes:
      - ${MINIO_DATA_ROOT_DIR}:/data
    ports:
      - '9000:9000'
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command: server /data

  minio-client:
    image: minio/mc
    depends_on:
      - minio-server
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config;
      /usr/bin/mc config host add myminio http://minio-server:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb myminio/${MINIO_BUCKET_NAME};
      "

  # nest-server:
  #   build:
  #     context: ./hygge-server
  #     dockerfile: Dockerfile
  #   container_name: nest-server-container
  #   environment:
  #     - PORT=${PORT}
  #     - MINIO_ENDPOINT=${MINIO_ENDPOINT}
  #     - MINIO_PORT=${MINIO_PORT}
  #     - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
  #     - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
  #     - MINIO_USE_SSL=${MINIO_USE_SSL}
  #     - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
  #     - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  #     - REFRESH_TOKEN=${REFRESH_TOKEN}
  #     - DATABASE_URL=${DATABASE_URL}
  #   ports:
  #     - '3000:${PORT}'
  #   depends_on:
  #     - postgres
  #     - minio-server
  #     - minio-client
  #   volumes:
  #     - ./src:/hygge-server/src

  # angular-app:
  #   build:
  #     context: ./hygge-app
  #     dockerfile: Dockerfile
  #   container_name: angular-app-container
  #   depends_on:
  #     - nest-server
  #   ports:
  #     - '8080:80'
volumes:
  postgres-data:

